# -*- coding: utf-8 -*-
"""LetsupgradeAssignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gzaKqR2iApMzIka1lgVzdHuIIcBzlimk
"""

#Lottery App in Python

print("Welcome To Lottery Games\n")

maxTicketAvailable = int(input(print("Enter the total number of participants you want to have in this lottery:")))
participants=[]
print(f'Total Number of People who can participate in game is  {maxTicketAvailable}')
for i in range(maxTicketAvailable):
  name=input(print("Please enter your name to get part in the lottery game :"))
  participants.append(name)

print(f'Sorry only {maxTicketAvailable} memebers can participate in this lottery.')
# game starts
print("---------------------------------------------------------------------")
print("Let's Start the Lottery")
print(f'Fianlly here is the list of the names of Participants Of Today lottery game is:{participants}')
import random
n = random.randint(0,maxTicketAvailable-1)

print("The today's Lottery Winner is :",participants[n])
print("Congragulations",participants[n])
print("Thank you for participating...")

